### ISSUE TITLE
Add support for an input rescaling to complement the output rescaling

### ISSUE THREAD

**Issue by jlperla** [HighDimensionalEconLab/econ_layers#17]
After #15   The current rescaling layesr doesn't do anything to the network on the inside.  So it can only represent the following, for a given `i` index.
```
x_i NN(x_1, .... x_N)
```
But we also want to be able to do things like `NN(x_1/x_i,, x_2/x_i, x_i, x_N/x_i)` or something like that to represent functions that are "close to" homogenous of degree 1 or `x_i NN(x_1/x_i, x_2/x_i, ... x_i, x_N/x_i)`.  That is, it divides everything by `x_i` except the `x_i` term, and then it rescales back by the `x_i`.  This is used in an "almost guess-and-verify" for homothetic problems.  Almost because it isn't forcing the `NN` to be independent of `x_i`... it just makes it easy.

Since there may be more elaborate types of rescaling, lets leave it relatively general and follow the pattern of the newly renamed outputrescaling in #15 

To do this
- [x] add in a new `InputRescalingLayer` which mimics the design of the `OutputRescalingLayer` exactly.  SOmething like https://github.com/HighDimensionalEconLab/econ_layers/blob/main/econ_layers/layers.py#L77-L83  becoming
```python
        self.input_rescaling_layer_args = input_rescaling_layer_kwargs
        self.output_rescaling_layer_args = output_rescaling_layer_kwargs
        self.InputRescalingLayer = InputRescalingLayer
        self.OutputRescalingLayer = OutputRescalingLayer

        if not self.InputRescalingLayer == None:
            self.rescale_input = InputRescalingLayer(**input_rescaling_layer_kwargs)
        else:
            self.rescale_input= None

        if not self.OutputRescalingLayer == None:
            self.rescale_output= OuputRescalingLayer(**output_rescaling_layer_kwargs)
        else:
            self.rescale_output= None
```
- [x] Then the forward is something like the following
```python
    def forward(self, input):
        rescaled_input = input if self.input_rescale is None else self.rescale_input(input)
        out = self.model(rescaled_input)  # pass through to the stored net
        if not self.RescalingLayer is None:
            return self.rescale_output(input, out)  # note that the rescaling doesn't use the rescaled inputs
        else:
            return out
```
- [x] Then, we can come up with a simple network to do this in the "guess almost homethetic" case.  Something like the following is a good place to start.  It would assume there is only a single value that is not rescaled.  Then you could do
```python
class RescaleAllInputsbyInput(nn.Module):
    def __init__(self, rescale_index):
        super().__init__()
        self.rescale_index = rescale_index
        
    def forward(self, x):
        rescale_scalar = 1 / x[self.rescale_index]
        return torch.stack(x[0:rescale_index]* rescale_scalar, x[rescale_index], x[rescale_index+1,:]* rescale_scalar) # or whatever it correct.
```

**Comment by janrosa1** [comment]
I built for the last one a more general structure, when there is a `rescaling layer` and `rescaled_layer`. code like:
```
class RescaleInputByInput(nn.Module):
    def __init__(self, rescale_index: int = 0, rescalled_index=1):
        super().__init__()
        self.rescale_index = rescale_index
        self.rescalled_index = rescalled_index

    def forward(self, x):
        if x.dim() == 1:
            x[self.rescalled_index] = x[self.rescalled_index] / x[self.rescale_index]
        else:
            x[:, [self.rescalled_index]] = (
                x[:, [self.rescalled_index]] / x[:, [self.rescale_index]]
            )
        return x
```

**Comment by janrosa1** [comment]
Ok, comming back to the old version
