### ISSUE TITLE
Code to ignore certain lightning warnings

### ISSUE THREAD

**Issue by jlperla** [HighDimensionalEconLab/econ_layers#5]
Right now we have
```
warnings.filterwarnings(
    "ignore",
    category=UserWarning,
    module="pytorch_lightning.trainer.data_loading",
    lineno=102,
)


warnings.filterwarnings(
    "ignore",
    category=UserWarning,
    module="pytorch_lightning.trainer.callback_hook",
    lineno=100,
)


warnings.filterwarnings(
    "ignore",
    category=UserWarning,
    module="torch.optim.lr_scheduler",
    lineno=129,
)
```
After a version bump we can revisit these and see what is still relevant.

The problem is that the lineno changes with each PL version (or torch for the lr_scheduler warning), so we can see if it is possible to do an "if" and then change it depending on what version we are at.  Then when new PL versions come out we can just add a case to the if...

**Comment by jlperla** [comment]
```
import warnings

warnings.filterwarnings("ignore", ".*does not have many workers.*")
```
That might be better.

The things to ignore are:
- [ ] https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/data_loading.py#L265-L270
- [ ] https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/data_loading.py#L106-L112
- [ ] https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/trainer.py#L1533-L1537

**Comment by jlperla** [comment]
@jbrightuniverse  Can this be removed now?  Did you test it on the other project?

**Comment by jbrightuniverse** [comment]
It can be removed, it works.
